KS-21-4 extension функция записывающая слово в файл
VladWhite22/KotlinSprint pull request #100
Opened 2024-12-08 17:25 UTC by VladWhite22

В общем хз как это заставить работать... Слишком много убил времени на этой задаче... А гит флоу нарушен потому что я накосячил с созданием проекта по боту, указал место создания папки с ботом  в папку с проектом котлин спринт

2024-12-09 20:12 UTC, ievetrovdev requested changes

2024-12-09 20:12 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task4.kt
> +fun File.addText(newText: String) {
На самом деле решение может быть довольно лаконичным, 
```
    val content = this.readText()
    this.writeText(newText.toLowerCase() + "\n" + content)
```

2024-12-11 00:06 UTC, VladWhite22 commented on src/main/kotlin/lesson_21/lesson21_task4.kt
> +fun File.addText(newText: String) {
Да, действительно все оказалось просто) Спасибо!)

2024-12-11 19:46 UTC, ievetrovdev approved these changes

2024-12-12 19:30 UTC, merged