KS-3-2 Приложение  персональных данных
VladWhite22/KotlinSprint pull request #12
Opened 2024-08-23 19:25 UTC by VladWhite22

Не понял задачу... Если сделал совсем не то, распиши пожалуйста условие задачи... Заранее спасибо!)

2024-08-25 07:18 UTC, ievetrovdev requested changes

2024-08-25 07:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3_task2.kt
> +     name = "Татьяна"
А зачем перезаписывать имя и отчество если оно не меняется. Эти переменные можно сделать неизменяемыми

2024-08-25 18:56 UTC, VladWhite22 commented on src/main/kotlin/lesson_3/lesson3_task2.kt
> +     name = "Татьяна"
А если она помимо фамилии еще и имя решит сменить?)

2024-08-26 07:22 UTC, ievetrovdev approved these changes
Так то оно так) но можно думать что сейчас у нас ТЗ только на смену фамилии) Делать лишнюю работу не нужно

2024-08-26 10:45 UTC, merged