KS-6-2 Таймер
VladWhite22/KotlinSprint pull request #26
Opened 2024-09-07 21:33 UTC by VladWhite22

2024-09-08 11:46 UTC, ievetrovdev requested changes

2024-09-08 11:46 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task2.kt
> +        time--
По условию вроде не нужно делать цикл. Может можно обойтись одним вызовом sleep?)

2024-09-08 22:53 UTC, VladWhite22 commented on src/main/kotlin/lesson_6/lesson6_task2.kt
> +        time--
Звучит душно, но мне показалось логичным в уроке по циклам использовать цикл)

2024-09-09 06:52 UTC, ievetrovdev approved these changes
Да) тут намек что не нужно мыслить шаблонно)

2024-09-09 10:10 UTC, merged