KS-7-1 Генератор случайных паролей
VladWhite22/KotlinSprint pull request #29
Opened 2024-09-13 11:26 UTC by VladWhite22

Не пришло в голову вариантов как это можно еще реализовать особенно через цикл...

2024-09-13 14:10 UTC, ievetrovdev requested changes

2024-09-13 14:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +    val numb1 = numbers.random()
делаешь пустую строку и в цикле добавляешь нее по два символа

2024-09-14 20:50 UTC, VladWhite22 commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +    val numb1 = numbers.random()
блин что то я вообще не врубаюсь как сделать, распиши пожалуйста подробнее...

2024-09-17 07:20 UTC, ievetrovdev approved these changes
Такой вариант хороший

2024-09-18 16:34 UTC, merged