KS-11-2 Класс пользователь замена пароля вывод свойств в консоль
VladWhite22/KotlinSprint pull request #49
Opened 2024-10-16 19:30 UTC by VladWhite22

2024-10-17 17:37 UTC, ievetrovdev requested changes

2024-10-17 17:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task2.kt
> +    lateinit var bio: String
Лучше избежать использования lateinit по возможности. Вот тут Кирилл наглядно объясняет почему https://youtu.be/0nXXUzMyF8c

2024-10-17 20:37 UTC, VladWhite22 commented on src/main/kotlin/lesson_11/lesson11_task2.kt
> +    lateinit var bio: String
Если честно я не понял что я сделал) Применил "Observable properties﻿" хз что это и как работает...

2024-10-18 16:10 UTC, ievetrovdev requested changes

2024-10-18 16:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task2.kt
> +    var bio: String by Delegates.observable("") {
Здорово, но здесь достаточно добавить это поле в конструктор и проинициализировать с помощью null или пустой строки)

2024-10-22 11:51 UTC, ievetrovdev approved these changes

2024-10-22 12:38 UTC, merged