KS-11-3 Проектирование сущностей для  социальной сети
VladWhite22/KotlinSprint pull request #50
Opened 2024-10-21 16:32 UTC by VladWhite22

2024-10-22 12:21 UTC, ievetrovdev requested changes

2024-10-22 12:21 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    var usersList: MutableList<User>? = null
Это свойство создано верно, но его надо поместить в качестве свойства основного конструктора.
К тому же значение можно сделать не null установив значение по умолчанию пустой список

2024-10-22 12:21 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    class User(
Класс пользователя нужен только для описания пользователя, методы относятся к классу комнаты

2024-10-22 12:21 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +        fun updateStatus() {
Согласно ТЗ метод обновления статуса (принимает имя пользователя и новый статус)

2024-10-23 09:16 UTC, ievetrovdev requested changes

2024-10-23 09:16 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +        userStatus = readln()
Все же метод уже принимает новый статус, запрашивать его повторно не нужно

2024-10-24 10:54 UTC, ievetrovdev requested changes

2024-10-24 10:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    fun updateStatus( userStatus: String){
Метод не соответствует ТЗ, обрати внимание что он должен принимать, логика изменения статуса могла бы выглядеть примерно так:
Ты ищешь пользователя в списке по имени и меняешь ему статус на новый, подумай как это можно реализовать, необходимо использовать подходящую extention функцию для этого

2024-10-24 15:41 UTC, VladWhite22 commented
если метод обновления статуса находится в теле класса комната то при вызове функции в main компилятор ее не видит, метод работает либо за классами либо в классе юзер... как его заставить работать в класcе комната?

2024-10-24 18:12 UTC, ievetrovdev commented
> если метод обновления статуса находится в теле класса комната то при вызове функции в main компилятор ее не видит, метод работает либо за классами либо в классе юзер... как его заставить работать в класcе комната?

Дело в том, что статус меняется у юзера в комнате, поэтому метод относится к классу комнаты
У тебя есть список пользователей в комнате, по нему ты выполняешь поиск определенного пользователя по его имени, и у него меняешь статус, изменяя значение его поля, класс User у нас только описывает пользователя

2024-10-24 18:13 UTC, ievetrovdev requested changes

2024-10-24 18:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +        if (nickname == this.nickname) {
Здесь нужно итерироваться по списку с пользователями и изменять у нужного статус

2024-10-24 20:33 UTC, VladWhite22 commented
метод вроде поборол, а вот с его вызовом осталась проблема...

2024-10-25 15:09 UTC, ievetrovdev requested changes

2024-10-25 15:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    fun User.updateStatus(nickname: String, userStatus: String) {
Метод должен выглядеть примерно так)

```
fun updateStatus(nickname: String, userStatus: String) {
    usersList.find { it == nickname }.status = userStatus
}
```

2024-10-26 09:04 UTC, ievetrovdev requested changes

2024-10-26 09:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    fun User.updateStatus(nick: String, userStatus: String) {
Ты пробовал запустить программу? Этого метода нет объекта User, он должен быть внутренним у класса Room

2024-10-26 19:53 UTC, ievetrovdev commented
Чтобы программа корректно работала, тебе необходимо убрать User перед функцией и оставить в таком виде:
`fun updateStatus(nick: String, userStatus: String)`
Соответственно, в момент вызова функции необходимо обращаться к объекту `room1` у которого есть данный метод
`room.updateStatus("Alex","Микрофон выключен")`

2024-10-27 18:27 UTC, ievetrovdev approved these changes
Да, теперь все верно!

2024-10-28 14:59 UTC, merged