KS-11-5 Реализовать класс работы форума
VladWhite22/KotlinSprint pull request #52
Opened 2024-10-23 14:10 UTC by VladWhite22

Не понял принцип паттерна "Строитель", вобщем по теме "Классы" совсем плыву....

2024-10-24 13:11 UTC, ievetrovdev requested changes
Хорошо, я тебя понял

Для начала давай вынесем классы `ForumMember` `ForumMesage` за пределы классы `Forum`

Эти классы не должны содержать методов, они лишь описывают сущности пользователя и сообщения, они должны быть внутри класса `Forum`, поскольку форум отвечает за создание, добавление и вывод информации

Внутри форума также должно быть поле с списком пользователей и сообщений, в которые должны добавляться новые объекты

Суть паттерна Строитель в том, что ты передаешь в функцию параметры, с которыми ты хочешь создать объект, а на выходе получаешь этот объект, созданный этой функцией

2024-10-24 21:55 UTC, VladWhite22 commented
Блин я не понимаю как работает передача между классами...

2024-10-25 17:55 UTC, ievetrovdev requested changes

2024-10-25 17:55 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +    fun createNewUser(userName: String,userId:Int) {
Почти все верно, но тебе нужно сначала создать объект пользователя внутри метода, а userId должен генерироваться автоматически - это внутреннее поле класса Forum, после создания объекта, его нужно добавить в список, а id должен увеличиваться на 1
Метод должен вернуть объект пользователя

2024-10-25 17:55 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +            forumMesage.message.add(message)
Тебе нужно также создавать объект сообщения и добавлять его в список

2024-10-28 13:51 UTC, ievetrovdev requested changes
Не забывай прожимать автоформатирование перед коммитом.

2024-10-28 13:51 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +class Forum (){
При отсутствии свойств в основном конструкторе круглые скобки опускаются

2024-10-28 13:51 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +//        val _forumMesage = ForumMesage(authoId = authoId, message = message)
Комментированный код лучше не оставлять, если на это нет действительно веских причин. Предлагаю почистить.

2024-10-28 13:51 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +
Пустые строки затесались, надо обращать на них внимание

2024-10-28 13:51 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +class ForumMember(
Предлагаю отделять классы от методов пустыми строками

2024-10-29 17:41 UTC, ievetrovdev requested changes

2024-10-29 17:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +    var authoId: Int,
Опечатка `authorId`

2024-10-29 17:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +class ForumMesage(
Опечатка `message`

2024-10-29 17:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +    val forumMesage: MutableList<ForumMesage> = mutableListOf()
Также опечатка, `message`

2024-10-29 17:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +    val forumMembers: MutableList<ForumMember> = mutableListOf()
Эти поля должны быть приватными и не торчать наружу

2024-10-29 17:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +        for (b in forumMembers.userName)
В текущей реализации программа не работает, ты видел что ты не можешь обратиться к этим полям напрямую?

2024-10-29 17:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +    fun printThread() {
Как быть с тем, что мы должны печатать сообщение и имя пользователя? Подсказка, их нужно брать из списка с сообщениями

2024-10-29 17:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +        forumMembers.find { it.userId == authoId }
Какую силу имеет это действие без дополнительной проверки?
Здесь нужно как-то проверить результат этого метода и при отсутствии пользователя, выйти из метода

2024-10-29 17:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +        val _forumMesage = ForumMesage(authoId = authoId, message = message)
Не логично получается, ты в любом случае создаешь сообщение, даже если пользователя нет, нужно сначала проверить есть ли пользователь на форуме и только потом создавать сообщение (еще нужно добавить поле с ником пользователя)

2024-10-29 17:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +    var message: String,
нужно добавить поле с ником пользователя

2024-10-31 16:38 UTC, ievetrovdev approved these changes

2024-10-31 19:25 UTC, merged