KS-13-3 Вывод компаний из телефонной книги
VladWhite22/KotlinSprint pull request #59
Opened 2024-10-29 22:59 UTC by VladWhite22

2024-10-30 18:19 UTC, ievetrovdev requested changes

2024-10-30 18:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_3.kt
> +class Companys(
Опечатка `Company`

2024-10-30 18:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_3.kt
> +    var name: String?,
Про поля уже писал ранее, нужно поправить

2024-10-30 18:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_3.kt
> +    var phoneNumber: Long?,
чем обуcловлен тут var?)

2024-10-30 18:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_3.kt
> +    for (company in listContacts)
Предлагаю использовать `mapNotNull`

2024-10-30 23:11 UTC, VladWhite22 commented on src/main/kotlin/lesson_13/lesson13_3.kt
> +    var phoneNumber: Long?,
тянется из предыдущих задач, уже не помню что то пытался сделать...)

2024-11-01 16:34 UTC, ievetrovdev requested changes

2024-11-01 16:34 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13_3.kt
> +    listContacts.mapNotNull { if (it.company != null) println(it.company) }
Чтобы сделать как сейчас, достаточно `forEach`  `mapNotNull` - вернет список без null результатов, давай воспользуемся им корректно

2024-11-02 15:12 UTC, ievetrovdev approved these changes

2024-11-03 22:26 UTC, merged