KS-15-2 Мониторинг погодных условий
VladWhite22/KotlinSprint pull request #66
Opened 2024-11-06 22:11 UTC by VladWhite22

2024-11-07 07:49 UTC, ievetrovdev requested changes

2024-11-07 07:49 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task2.kt
> +    fun SendMassege(temperature: Temperature, precipitationAmount: PrecipitationAmount) {
Метод должен принимать объекты температуры или осадков, одним параметром. Для этого у нас и есть базовый класс WeatherStationStats, который их объединяет. И внутри уже распределять какой именно сообщение отправляется.

2024-11-07 14:30 UTC, VladWhite22 commented on src/main/kotlin/lesson_15/lesson15_task2.kt
> +    fun SendMassege(temperature: Temperature, precipitationAmount: PrecipitationAmount) {
В таком случае не получается вывести индивидуальные поля классов наследников...

2024-11-08 06:50 UTC, ievetrovdev requested changes

2024-11-08 06:50 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task2.kt
> +        weatherList.add(parametr)
Почему же не можем? Temperature и PrecipitationAmount наследники WeatherStationStats. То есть переменная parametr может быть или Temperature или PrecipitationAmount. можем с помошью условия точно узнать точно if(parametr is Temperature) Дальше уже можно работать как с переменной класса Temperature

2024-11-08 17:55 UTC, VladWhite22 commented on src/main/kotlin/lesson_15/lesson15_task2.kt
> +        weatherList.add(parametr)
Никогда бы не догадался...) То есть в ситуации когда есть суперкласс необходимо обозначать над объектом какого производного класса выполняется действие...

2024-11-09 05:48 UTC, ievetrovdev requested changes

2024-11-09 05:48 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson15_task2.kt
> +        for (wether in weatherList) {
Что то у тебя сейчас много лишнего
1. Зачем вообще нужен список, в который ты добавляешь 1 элемент, а потом по нему проходишь? Можно же сразу переменную p arametr проверять в условии if (wether is Temperature) и if (wether is PrecipitationAmount) 
2. Если уж ты делаешь цикл, зачем делать два последовательных
, два условия можно поместить в один цикл

2024-11-11 06:50 UTC, ievetrovdev approved these changes

2024-11-11 13:26 UTC, merged