KS-16-4 Заказ в интернет магазине
VladWhite22/KotlinSprint pull request #73
Opened 2024-11-12 23:20 UTC by VladWhite22

Вот что то я сделал... Но я же все равно могу вызвать функцию в min напрямую из класса... Может как то нужно сделать через функции высокого порядка?..

2024-11-13 13:12 UTC, ievetrovdev requested changes

2024-11-13 13:12 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson16_task4.kt
> +    fun changeStatus(newStatus: String) {
Цель продемонстрировать реализацию инкапсуляции, когда мы не вызываем публичный метод, а вызываем вспомогательный, который в свою очередь дергает другой приватный метод класса и передает в него необходимые данные. То есть чтобы нельзя было сразу напрямую обратиться в скрытый метод.

2024-11-14 07:10 UTC, ievetrovdev requested changes

2024-11-14 07:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson16_task4.kt
> +        return Order().changeStatus(newStatus)
что то странное тут у тебя
1. Зачем что то возвращать
2. Зачем в методе создавать новый объект? 
Публичный метод должен только вызывать приватный, и передавать в него предполагаемый ответ сервера.

2024-11-14 18:50 UTC, VladWhite22 commented on src/main/kotlin/lesson_16/lesson16_task4.kt
> +        return Order().changeStatus(newStatus)
Перемудрил...

2024-11-15 07:21 UTC, ievetrovdev approved these changes

2024-11-15 13:43 UTC, merged