KS-17-2 Класс корабля с кастомным сеттером имени
VladWhite22/KotlinSprint pull request #75
Opened 2024-11-14 22:08 UTC by VladWhite22

2024-11-15 22:42 UTC, ievetrovdev requested changes

2024-11-15 22:42 UTC, ievetrovdev commented on src/main/kotlin/lessson_17/lesson17_task2.kt
> +            if (value != "Непотопляемый")
Условие не нужно

2024-11-15 23:55 UTC, VladWhite22 commented on src/main/kotlin/lessson_17/lesson17_task2.kt
> +            if (value != "Непотопляемый")
А если пользователь вводит то же самое имя?

2024-11-16 23:22 UTC, ievetrovdev commented on src/main/kotlin/lessson_17/lesson17_task2.kt
> +            if (value != "Непотопляемый")
Ты тут как минимум сравниваешь не с тем значением, что уже указано в поле, а просто с константой "Непотопляемый", да и в целом, лучше лишний раз сказать, что нельзя менять, чем вводить в заблуждение этим особенным случаем

2024-11-16 23:22 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-11-17 22:17 UTC, merged